const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
});

const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRAND: 'BRAND',
  PARTICIPANT: 'PARTICIPANT'
});

const PROFILE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
});

const PROJECT_STATUS = Object.freeze({
  DRAFT: 'draft',
  PUBLISHED: 'published',
  ARCHIVED: 'archived'
});

const PROJECT_MODE = Object.freeze({
  MARKETPLACE: 'MARKETPLACE',
  D2C: 'D2C'
});

const APPLICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PURCHASED: 'PURCHASED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
});

const ALLOCATION_STATUS = Object.freeze({
  RESERVED: 'RESERVED',
  PURCHASED: 'PURCHASED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
});

const PROOF_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
});

const PAYOUT_STATUS = Object.freeze({
  ELIGIBLE: 'ELIGIBLE',
  IN_BATCH: 'IN_BATCH',
  EXPORTED: 'EXPORTED',
  PAID: 'PAID',
  FAILED: 'FAILED'
});

const SUPPORT_TICKET_STATUS = Object.freeze({
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
});

module.exports = {
  HTTP_STATUS,
  ROLES,
  PROFILE_STATUS,
  PROJECT_STATUS,
  PROJECT_MODE,
  APPLICATION_STATUS,
  ALLOCATION_STATUS,
  PROOF_STATUS,
  PAYOUT_STATUS,
  SUPPORT_TICKET_STATUS
};